import random
import time
import os

def eleccion():
    time.sleep(2)
    print("                                  ")                                
    print("                                  ")      
    print("                                  ")                  
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    O    O    ▓▓        ")
    print("        ▓▓   ╔══════╗   ▓▓        ")
    print("        ▓▓   ╚══════╝   ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    O    O    ▓▓        ")
    print("        ▓▓   ╔══════╗   ▓▓        ")
    print("        ▓▓   ╚══════╝   ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    O    O    ▓▓        ")
    print("        ▓▓   ╔══════╗   ▓▓        ")
    print("        ▓▓   ╚══════╝   ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("         ▓▓▓▓▓▓▓▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    O    O    ▓▓        ")
    print("        ▓▓   ╔══════╗   ▓▓        ")
    print("        ▓▓   ╚══════╝   ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("         ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    O    O    ▓▓        ")
    print("        ▓▓   ╔══════╗   ▓▓        ")
    print("        ▓▓   ╚══════╝   ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("         ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓▓               ")
    print("                   ▓▓             ")
    print("                    ▓▓            ")
    print("                     ▓▓           ")
    print("                      ▓▓          ")
    print("                       ▓▓         ")
    print("                                  ")
    time.sleep(2)
    os.system("cls")
                                    
    print("                                  ")                                
    print("          MMMMMMMMMMMMMM          ")      
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓          ")                  
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    ┼    ┼    ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("        ▓▓    [----]    ▓▓        ")
    print("        ▓▓              ▓▓        ")
    print("          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("         ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("                ▓▓                ")
    print("               ▓▓▓▓               ")
    print("             ▓▓    ▓▓             ")
    print("            ▓▓      ▓▓            ")
    print("           ▓▓        ▓▓           ")
    print("          ▓▓          ▓▓          ")
    print("         ▓▓            ▓▓         ")
    print("                                  ")
    
    '''     if opcion ==1:
        print("└─┬├─┼┬┼┴└┐─┼┬┴┼└┐┴├┼─┼┴└┬─")
    elif opcion == 2:
        print("└┼├┼┼└┬┴─├┼┬┼└─┴┴┬┬┼┼┴┐├├┬┴")
    elif opcion == 3:
        print("├├┬┼└┴┴┼├┼┐┬┴─┼┴├─┬┴└┐┬┼├├┬")
    elif opcion == 4:
        print("┼┼┴├┬┬┴┐┼─├└─┴┼┴└┐──┬┼└┴─├┴")
    elif opcion == 5:
        print("└┼─┬├┼├┬┬┴└─┴└┼┬┬┴┐──└┼┬┴┼└")
    else:
        print("└─┼─┼──┼┴┬─└┴┼┼┼└└─├┴┼├┴┼┬┐") '''

def run():
    '''     for i in range(12):
        eleccion(random.randrange(1,6)) '''
    eleccion()


if __name__ == '__main__':
    run()